modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="epicarmory"
# ${file.jarVersion} will substitute the value of the Implementation-Version as read from the mod's JAR file metadata
version="0.0.1-1.19.2"
displayName="Vancomb's Epic Armory"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java"
authors="Vancomb"
description='''
'''

[[dependencies.epicarmory]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.epicarmory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
